stages:
  - build

variables:
  REGISTRY: hub.alterway.fr

before_script:
  - if [[ "$CI_BUILD_REF_NAME" != master ]]; then REGISTRY="$REGISTRY/$CI_BUILD_REF_NAME"; fi

build:
  stage: build
  script:
    - docker build --pull -t $REGISTRY/php:5.6-fpm 5.6-fpm/
    - docker build -t $REGISTRY/php:5.6-fpm-extra 5.6-fpm-extra/
    - docker build --pull -t $REGISTRY/php:5.6-cli 5.6-cli/
    - docker build --pull -t $REGISTRY/php:5.6-apache 5.6-apache/
    - docker build --pull -t $REGISTRY/php:5.5-fpm 5.5-fpm/
    - docker build -t $REGISTRY/php:5.5-fpm-extra 5.5-fpm-extra/
    - docker build --pull -t $REGISTRY/php:5.5-cli 5.5-cli/
    - docker build --pull -t $REGISTRY/php:5.5-apache 5.5-apache/
    - docker build --pull -t $REGISTRY/php:5.4-fpm 5.4-fpm/
    - docker build --pull -t $REGISTRY/php:5.4-cli 5.4-cli/
    - docker build --pull -t $REGISTRY/php:5.4-apache 5.4-apache/
    - docker build --pull -t $REGISTRY/php:5.3-fpm 5.3-fpm/
    - docker build -t $REGISTRY/php:5.3-fpm-extra 5.3-fpm-extra/
    - docker push $REGISTRY/php:5.6-fpm
    - docker push $REGISTRY/php:5.6-fpm-extra
    - docker push $REGISTRY/php:5.6-cli
    - docker push $REGISTRY/php:5.6-apache
    - docker push $REGISTRY/php:5.5-fpm
    - docker push $REGISTRY/php:5.5-fpm-extra
    - docker push $REGISTRY/php:5.5-cli
    - docker push $REGISTRY/php:5.5-apache
    - docker push $REGISTRY/php:5.4-fpm
    - docker push $REGISTRY/php:5.4-cli
    - docker push $REGISTRY/php:5.4-apache
    - docker push $REGISTRY/php:5.3-fpm
    - docker push $REGISTRY/php:5.3-fpm-extra
  only:
    - preprod
    - master
